<a href="https://colab.research.google.com/github/varshasisodiya16-arch/first-repository/blob/main/NUMPHY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy is udes for working with arrays.
#it is short for"numericsl python".
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
# checking numpy version
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
# different ways to create numpy array
# 1 using numpy function
# 2 CONVERSION from python structure like list;
# 3 usind special library  funtions.
# CREATE 1D ARRAY.
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
# create 2d array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)# give dimention of array.

[[1 2 3]
 [4 5 6]]
2


In [ ]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=2)
print (arr)

[[1 2 3 4]]


In [ ]:
#numpy indexing
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
# add element by index
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2]+arr[1])

5


In [ ]:
# access 2d array
import numpy as np
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr[0,1])

2


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print (arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [ ]:
# numpy array slicing
import numpy as np
arr=np.array([10,20,30,40,50,60,75])
print(arr[1:5])
#slice idx from 4
print(arr[4:])
# till 3
print(arr[:4])

[20 30 40 50]
[50 60 75]
[10 20 30 40]


In [ ]:
# negative slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])
# retunr every other elements from the entire array
print(arr[::2])

[5 6]
[1 3 5 7]


In [ ]:
# slicing  2d array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])

[7 8 9]
[3 8]


In [ ]:
# datatype
import numpy as np
arr=np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# datatype
import numpy as np
arr=np.array([1,2,3,4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32
